### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by ghost** [SublimeText/VintageEx#36]
When Sublime text starts, there is an error in console:

Reloading plugin C:\Users\Peter\AppData\Roaming\Sublime Text 2\Packages\VintageEx\setup.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\setup.py", line 11, in <module>
    from distutils import log, dir_util, dep_util, file_util, archive_util
ImportError: No module named distutils

The plugin still works, but maybe this error is connected with some other bugs

**Comment by guillermooo** [comment]
This will only happen with clones of this repository. If you used the _.sublime-package_ pointed at from the README, it would not happen. The error should be harmless, though. ST is scanning the _setup.py_ file for `*Command` classes and thus the code gets run, which in turn tries to locate libraries unavailable under ST.

You don't _have_ to use the _.sublime-package_ just mentioned, but that's the package intended for end users, so to speak.

**Comment by ghost** [comment]
I see now, error is gone. 

I saw package from README, but I just found it easier to install it through Package Control.

**Comment by guillermooo** [comment]
I have to figure out a way to avoid the error in _setup.py_. Ironically, it's just hack to make the _.sublime-package_ release more convenient :)

**Comment by s-trooper** [comment]
same problem. tried both manuell install in "Installed Packages" and with package control
