### ISSUE TITLE
Please add support to Sublime Text 3

### ISSUE THREAD

**Issue by ld** [SublimeText/VintageEx#52]
Somehow, it doesn't work under ST3.
Please fix it. Thank you.

**Comment by egyptianbman** [comment]
I also am finding that this is not functional in Sublime Text 3 and would greatly appreciate it; thanks!

Below is what I'm getting on installation:

reloading plugin VintageEx.ex_commands
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/beshoy/Library/Application Support/Sublime Text 3/Installed Packages/VintageEx.sublime-package/ex_commands.py", line 152
    print e
          ^
SyntaxError: invalid syntax
reloading plugin VintageEx.ex_search_cmd
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/beshoy/Library/Application Support/Sublime Text 3/Installed Packages/VintageEx.sublime-package/ex_search_cmd.py", line 146
    except RuntimeError, e:
                       ^
SyntaxError: invalid syntax
reloading Packages/VintageEx/Preferences.sublime-settings
reloading plugin VintageEx.setup
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/beshoy/Library/Application Support/Sublime Text 3/Installed Packages/VintageEx.sublime-package/setup.py", line 51
    raise DistutilsExecError, \
                            ^
SyntaxError: invalid syntax
reloading plugin VintageEx.test_runner
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/beshoy/Library/Application Support/Sublime Text 3/Installed Packages/VintageEx.sublime-package/test_runner.py", line 6, in <module>
ImportError: No module named 'StringIO'
reloading plugin VintageEx.vintage_ex
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "/Users/beshoy/Library/Application Support/Sublime Text 3/Installed Packages/VintageEx.sublime-package/vintage_ex.py", line 51
    print ex_cmd
               ^

**Comment by guillermooo** [comment]
Use this intead: https://github.com/guillermooo/Vintageous

**Comment by egyptianbman** [comment]
Thank you!
